server:
  port: 8082

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kunalsuryawanshi/config-server.git
          clone-on-start: true
